# Generated by Django 5.1.5 on 2025-01-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Driver', 'Driver')], default='Customer', max_length=10),
        ),
    ]
